Django/project_1/NewsPortal/NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path("accounts/", include("allauth.urls")),
<<<<<<< Updated upstream
=======
    path('', include('subscriptions.urls'), name='subscriptions'),
>>>>>>> Stashed changes
    path('posts/', include('news.urls')),
    path('', HomePage.as_view(), name='homepage'),
]

Django/project_1/NewsPortal/news/urls.py
from django.urls import path
<<<<<<< Updated upstream

from .views import * 

=======
from .views import (
    PostsList,
    PostSearch,
    PostDetail,
    PostCreate,
    PostUpdate,
    PostDelete,
    PostArticleCreate,
    PostArticleUpdate,
    PostArticleDelete,
    PostNewsCreate,
    PostNewsUpdate,
    PostNewsDelete,

)
>>>>>>> Stashed changes


urlpatterns = [
   path('', PostsList.as_view(), name='posts'), 
   path('search/', PostSearch.as_view(), name='search'), 
   path('<int:pk>', PostDetail.as_view(), name='post_detail'),
   path('articles/create/', PostArticleCreate.as_view(), name='article_create'),
   path('news/create/', PostNewsCreate.as_view(), name='news_create'),
   path('create/', PostCreate.as_view(), name='post_create'),
   path('edit/<int:pk>/', PostUpdate.as_view(), name='post_edit'),
   path('articles/edit/<int:pk>/', PostArticleUpdate.as_view(), name='article_edit'),
   path('news/edit/<int:pk>/', PostNewsUpdate.as_view(), name='news_edit'),
   path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('news/delete/<int:pk>/', PostNewsDelete.as_view(), name='news_delete'),
<<<<<<< Updated upstream
   path('articles/delete/<int:pk>/', PostArticleDelete.as_view(), name='article_delete'),
   
]
=======
   path('articles/delete/<int:pk>/',
        PostArticleDelete.as_view(), name='article_delete'),
]
>>>>>>> Stashed changes

Django/project_1/NewsPortal/subscriptions/urls.py
from django.urls import path

from .views import subscriptions

urlpatterns = [
    path('subscriptions/', subscriptions, name='subscriptions'),
]

Django/project_1/NewsPortal/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import pgettext_lazy, gettext_lazy
from django.utils.translation import gettext as _




class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default = 0)

    def __str__(self) -> str:
        return self.user.username
    

    def uppdate_rating(self):

        if Post.objects.filter(author=self).exists():
            __posts_rating = Post.objects.filter(author=self).values('rating')
            self.rating += sum(item['rating'] for item in __posts_rating)*3
            self.save()
        
        if Comment.objects.filter(user=self.user).exists():
            __comments_rating = Comment.objects.filter(user=self.user).values('rating')
            self.rating += sum(item['rating'] for item in __comments_rating)
            self.save()

        if Comment.objects.filter(post__author=self).exists():
            __postComments_rating = Comment.objects.filter(post__author=self).values('rating')
            self.rating += sum(item['rating'] for item in __postComments_rating)
            self.save()
                    

class Category(models.Model):
    category = models.CharField(max_length = 24, unique = True)

    def __str__(self) -> str:
        return self.category

class Post(models.Model):

    class PostType(models.TextChoices):

        news = 'NE', gettext_lazy('News')
        article = 'AR', gettext_lazy('Article')

<<<<<<< Updated upstream

    author = models.ForeignKey(Author, on_delete = models.CASCADE)
    choise = models.CharField(max_length = 2, choices=PostType, default = PostType.news)
    creation_date = models.DateTimeField(auto_now_add = True)
    post_header = models.CharField(max_length=64)
    post_text = models.TextField(default='Some text', max_length=512)
    rating = models.IntegerField(default=0)

    category = models.ManyToManyField(Category, through = 'PostCategory')
=======
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    choise = models.CharField(
        max_length=2,
        choices=PostType,
        default=PostType.news
    )
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name=pgettext_lazy('Creation date', 'Date'))
    post_header = models.CharField(max_length=64, verbose_name=pgettext_lazy('Header', 'Post header'), help_text=_('Post header place'))
    post_text = models.TextField(default='Some text', max_length=512)
    rating = models.IntegerField(default=0)
    
    category = models.ManyToManyField(Category, through='PostCategory', verbose_name=pgettext_lazy('Category', 'Post category'))

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'post-{self.pk}')
        # затем удаляем его из кэша, чтобы сбросить его
>>>>>>> Stashed changes

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        if len(self.post_text) > 124:
            return f"{str(self.post_text)[:124]}..."
        else:
            return f"{str(self.post_text)}"

    def __str__(self):
<<<<<<< Updated upstream
        return f'Название: {self.post_header}, Автор: {self.author.user.username}, Рейтинг: {self.rating}'
    
=======
        return (f'Name: {self.post_header}, Author: {self.author.user.username}, Rating: {self.rating}')

>>>>>>> Stashed changes
    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=64)
    creation_date = models.DateTimeField(auto_now_add = True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

Django/project_1/NewsPortal/subscriptions/models.py
from django.db import models

# Create your models here.

Django/project_1/NewsPortal/subscriptions/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.db.models import Exists, OuterRef
from django.urls import reverse_lazy
from news.models import *

# Create your views here.
@login_required
@csrf_protect
def subscriptions(request):
    if request.method == 'POST':
        category_id = request.POST.get('category_id')
        category = Category.objects.get(id=category_id)
        action = request.POST.get('action')

        if action == 'subscribe':
            Subscribers.objects.create(user=request.user, category=category)
        elif action == 'unsubscribe':
            Subscribers.objects.filter(
                user=request.user,
                category=category,
            ).delete()

    categories_with_subscriptions = Category.objects.annotate(
        user_subscribed=Exists(
            Subscribers.objects.filter(
                user=request.user,
                category=OuterRef('pk'),
            )
        )
    ).order_by('category')
    return render(
        request,
        'subscriptions.html',
        {'categories': categories_with_subscriptions},
    )

Django/project_1/NewsPortal/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Статьи за неделю</h1>
    <ul>
    {% for post in posts %}
            <li><a href="{{ link }}{{ post.get_absolute_url }}">Новый пост: {{ post.post_header }}</a></li>
    {% endfor %}
    </ul>
</body>
</html>

Django/project_1/NewsPortal/templates/default.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}
{% load custom_tags %}
{% load tz %}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple app</title>
    {% load custom_filters %}
    {% load custom_tags %}
<<<<<<< Updated upstream:Django/project_1/NewsPortal/templates/flatpages/default.html
    {% load static %}
=======
    {% load cache %}
>>>>>>> Stashed changes:Django/project_1/NewsPortal/templates/default.html
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body {% if current_time.hour >= 19 or current_time.hour <= 7 %} style="background-color: #4B8BBE" {% else %} style="background-color: #FFE873" {% endif %}>
        <header class="wrapper">
        <div class="container">
            <nav class="header_nav"> 
<<<<<<< Updated upstream:Django/project_1/NewsPortal/templates/flatpages/default.html
                <a href="/home" style="min-width: 15px; min-height: 15px; text-align: center;"><img src="https://pythonz.net/media/img/events/thumbs/180x236/db5c67d4-1755-461e-951f-85c82f8d4607.jpeg" alt="Img" width="50px" height="50px"></a>
                <ul>
=======
                <a href="{% url 'homepage' %}" style="min-width: 15px; min-height: 15px; text-align: center;"><img src="https://pythonz.net/media/img/events/thumbs/180x236/db5c67d4-1755-461e-951f-85c82f8d4607.jpeg" alt="Img" width="50px" height="50px"></a>
                
                <ul class="header_nav__ul">
>>>>>>> Stashed changes:Django/project_1/NewsPortal/templates/default.html
                    <li>
                        {% url 'homepage' as url_home %}
                        <a href="{% url 'homepage' %}" class="{% navactive request 'homepage' %}">{% trans 'Home' %}</a>
                    </li>
                    <li>
                        {% url 'posts' as url_posts %}
                        <a href="{% url  'posts' %}" class="{% navactive request 'posts' %}">{% trans 'Posts' %}</a>
                    </li>
                    <li>
                        {% url 'search' as url_search %}
                        <a href="{% url 'search' %}" class="{% navactive request 'search' %}">{% trans 'Search' %}</a>
                    </li>
                </ul>
<<<<<<< Updated upstream:Django/project_1/NewsPortal/templates/flatpages/default.html
=======
                <div class="account">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'subscriptions' %}">{{ request.user.username }}</a>
                        <img src="{% static 'images/user-profile_login.png' %}" alt="My image" width="25" height="25"/>
                        <a href="http://127.0.0.1:8000/accounts/logout/">{% trans 'logout' %}</a>
                    {% else %}
                        <a href="http://127.0.0.1:8000/accounts/login/">{% trans 'login' %}</a>
                        <img src="{% static 'images/user-profile_unlogin.png' %}" alt="img" width="25px" height="25px">
                    {% endif %}
                    
                    
                </div>
>>>>>>> Stashed changes:Django/project_1/NewsPortal/templates/default.html
            </nav>
        </div>
    </header>
    <div class="content wrapper">
        <div class="container">
            <div class="container-content">
                <div class="container-content_header">
                    <h1>
                        {% block title %}
                            {{ flatpage.title }}
                        {% endblock title %}
                    </h1>
                </div>
                <div class="container-content_body">
                    {% block content %}
                        {{ flatpage.content }}
                    {% endblock content %}
                </div>
            </div>
        </div>
    </div>

    {% if 'posts' in request.get_full_path  %}
    <div class="pagination">
        <span class="step-links">
            
                {% if page_obj.has_previous %}
                    <a href="?{% url_replace page=1 %}">&laquo; {% trans 'first' %}</a>
                    <a href="?{% url_replace page=page_obj.previous_page_number %}">{% trans 'previous' %}</a>
                {% endif %}
        
                <span class="current">
                    {% if page_obj.has_previous %}
                        {{ page_obj.previous_page_number}}
                    {% endif %}

                    <<{{page_obj.number}}>>

                    {% if page_obj.has_next %}
                        {{ page_obj.next_page_number}}
                    {% endif %}
                </span>
        
                {% if page_obj.has_next %}
                    <a href="?{% url_replace page=page_obj.next_page_number %}">{% trans 'next' %}</a>
                    <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{% trans 'last'%} &raquo;</a>
                {% endif %}
        </span>
    </div>
    {% endif %}
</body>
<footer>

</footer>
</html>

Django/project_1/NewsPortal/templates/home.html
{% extends 'default.html' %}
{% load tz %}
{% load i18n %}
 
{% block title %}
{% endblock title%}

{% block content %}
<form action="{% url 'set_language' %}" method="POST"> {% csrf_token %} <!-- Не забываем по csrf_token для POST запросов -->
    <input type="hidden" name="next" value="{{ redirect_to }}">
    {% get_current_language as LANGUAGE_CODE %}
    <select name="language" id="">
        {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
        {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->
        {% get_current_language as LANGUAGE_CODE %}
        {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
            <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                {{ language.name_local }} - {{ language.code }}
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="{% trans 'set' %}">
</form>
    {% get_current_timezone as TIME_ZONE %}
<form action="" method="POST">
    {% csrf_token %}
    <label for="timezone">Time zone:</label>
    <select name="timezone">
        {% for tz in timezones %}
        <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Set">
</form>
 
    {{ TIME_ZONE }}
    {{ current_time|timezone:TIME_ZONE }} <!-- Отображаем время в выбранном часовом поясе  -->


    {{ models }}
{% endblock content %}

Django/project_1/NewsPortal/templates/post.html
{% extends 'default.html' %}
{% load custom_filters %}
{% load i18n %}
{% load tz %}

{% block title %}
    {{post.post_header}}
{% endblock title %}

{% block content %}
    <div class="post-container">
        <div class="post">
            <h1>{{ post.post_header }}</h1>
<<<<<<< Updated upstream
            <p>Дата публикации: {{ post.creation_date|date:"d.m.y" }}</p>
            <hr style="margin-top: 5px; margin-bottom: 5px;">
            <p>{{ post.post_text|censor }}</p>
            {% if post.choise == 'AR' %}
                <p><a href="{% url 'article_delete' pk=post.id%}">Удалить: </a></p>
                <p><a href="{% url 'article_edit' pk=post.id%}">Изменить: </a></p>
            {% elif post.choise == 'NE' %}
                <p><a href="{% url 'news_delete' pk=post.id%}">Удалить: </a></p>
                <p><a href="{% url 'news_edit' pk=post.id%}">Изменить: </a></p>
=======
            <p>{% trans 'Creation date:' %} {{ post.creation_date|date:"d.m.y" }}</p>
            <hr style="width: 100%; margin-top: 25px; margin-bottom: 25px;">
            <p>{{ post.post_text|censor }}</p>
            {% if post.choise == 'AR' %}
                {% if perms.news.add_post and perms.news.create_post %}
                <div class="post-edit">
                    <p class="post-edit_delete"><a href="{% url 'article_delete' pk=post.id%}"> {% trans 'Delete' %} </a></p>
                    <p class="post-edit_edit"><a href="{% url 'article_edit' pk=post.id%}">{% trans 'Edit' %}</a></p>
                </div>
                {% endif %}
            {% elif post.choise == 'NE' %}
                {% if perms.news.add_post and perms.news.create_post %}
                <div class="post-edit">
                    <p class="post-edit_delete"><a href="{% url 'news_delete' pk=post.id%}">{% trans 'Delete' %}</a></p>
                    <p class="post-edit_edit"><a href="{% url 'news_edit' pk=post.id%}">{% trans 'Edit' %}</a></p>
                </div>
                {% endif %}
>>>>>>> Stashed changes
            {% endif %}
        </div>
    </div>
{% endblock content %}

Django/project_1/NewsPortal/templates/post_article_delete.html
{% extends 'default.html' %}
{% load i18n %}

{% block content %}
<h1>{% trans 'Article delete' %}</h1>
{% if post.choise == 'AR' %}
<form action="" method="post" style="text-align: center;">
    {% csrf_token %}
    <p>{% trans 'Delete' %} "{{ post.post_header }}"?</p>
    <input type="submit" value="{% trans 'Delete' %}" />
</form>
{% else %}
    <h2>Это не статья!</h2>
{% endif %}
{% endblock content %}

Django/project_1/NewsPortal/templates/post_article_edit.html
{% extends 'default.html' %}
{% load i18n %}

{% block title %}

    {% if post.choise %}
    <h1>{% trans 'Edit article' %}</h1>
    {% else %}
    <h1>{% trans 'Create article' %}</h1>
    {% endif %}
    
{% endblock title %}

{% block content %}
{% if post.choise == 'AR' or post.choise is None %}
<form action="" method="post" style="text-align: center;">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans 'Save' %}" />
</form>
{% else %}
    <h2>Это не статья!</h2>
{% endif %}
{% endblock content %}

Django/project_1/NewsPortal/templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <span>Новый пост</span>
        <a href="{{ link }}">По ссылке: {{ title }}</a>
        <p>{{ text }}</p>
    </div>
</body>
</html>

Django/project_1/NewsPortal/templates/post_delete.html
{% extends 'default.html' %}
{% load i18n %}

{% block content %}
<h1>{% trans 'Delete post' %}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>{% trans 'Delete' %} "{{ post.post_header }}"?</p>
    <input type="submit" value="{% trans 'Delete' %}" />
</form>
{% endblock content %}

Django/project_1/NewsPortal/templates/post_edit.html
{% extends 'default.html' %}
{% load i18n %}

{% block title %}
    <h1>{% trans 'Edit post' %}</h1>
{% endblock title %}

{% block content %}
<form action="" method="post" style="text-align: center;">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans 'Save' %}" />
</form>
{% endblock content %}

Django/project_1/NewsPortal/templates/post_news_delete.html
{% extends 'default.html' %}
{% load i18n %}

{% block content %}
<h1>{% trans 'News delete' %}</h1>
{% if post.choise == 'NE' %}
<form action="" method="post" style="text-align: center;">
    {% csrf_token %}
    <p>{% trans 'Delete' %} "{{ post.post_header }}"?</p>
    <input type="submit" value="{% trans 'Delete' %}" />
</form>
{% else %}
    <h2>Это не новость!</h2>
{% endif %}
{% endblock content %}

Django/project_1/NewsPortal/templates/post_news_edit.html
{% extends 'default.html' %}
{% load i18n %}

{% block title %}

    {% if post.choise %}
    <h1>{% trans 'Edit news' %}</h1>
    {% else %}
    <h1>{% trans 'Create news' %}</h1>
    {% endif %}
    
{% endblock title %}

{% block content %}
{% if post.choise ==  'NE' or post.choise is None %}
<form action="" method="post" style="text-align: center;">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans 'Save' %}" />
</form>
{% else %}
    <h2>Это не новость!</h2>
{% endif %}
{% endblock content %}

Django/project_1/NewsPortal/templates/post_search.html
{% extends 'default.html' %} 
{% load custom_filters %}
{% load custom_tags %}
{% load i18n %}
 
{% block title %}
    <h1>{% trans 'Find:' %}</h1>
{% endblock title %}
 
{% block content %}
<form method="get" action="{% url 'posts' %}">

    {{ filterset.form.non_field_errors }}
    {{ filterset.form.post_header__icontains.errors }}
    {{ filterset.form.as_p}}

    <input type="submit" value="{% trans 'Find' %}" />
</form>
{% endblock content %}

Django/project_1/NewsPortal/templates/posts.html
{% extends 'default.html' %} 
{% load custom_filters %}
{% load custom_tags %}
{% load i18n %}
{% load tz %}
 
{% block title %}
    <h1>{% trans 'Posts:' %}{{posts.count}}</h1>
    {% for category in categories %}
        <span>{{category}}</span>
    {% endfor %}
    
{% endblock title %}
 
{% block content %}

    <div class="news-form">
        <div class="news-form_links">
            <span>{% trans 'Add' %}: </span>
            <a href="{% url 'article_create' %}">{% trans 'article' %}</a>
            <a href="{% url 'news_create' %}">{% trans 'news' %}</a>
        </div>
        <form class="news-search" action="" method="get" >

            {{ filterset.form.non_field_errors }}
            {{ filterset.form.post_header__icontains.errors }}
            {{ filterset.form.post_header.label}}
            {{ filterset.form.post_header}}
    
            <input type="submit" value="{% trans 'Find' %}"/>
    </div>

    {% if posts %}

    <div class="posts-container">
        {% for post in posts %}
            <div {% if forloop.last and not posts.count|divisibleby:2 %} class="posts long"{% else %} class="posts" {% endif %}>
             <h1 class="posts-header"><a href={{post.id}}>{{ post.post_header}}</a></h1>
                <span style="font-size: 18px;">{{ post.creation_date|date:'M d Y'}} {{post.choise}}</span>
<<<<<<< Updated upstream
                <p>{{ post.post_text|truncatewords:30|censor }}</p>
=======
                <p style="word-break: break-all;">{{ post.post_text|truncatewords:30|censor }}</p>
>>>>>>> Stashed changes
            </div>
        {% endfor %}
    </div>
    {% endif %}
{% endblock content %}

Django/project_1/NewsPortal/templates/subscriptions.html
{% extends 'default.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Subscriptions' %}
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>{% trans 'Subscribe' %}</button>
                    <button name="action" value="unsubscribe">{% trans 'Describe' %}</button>
                {% else %}
                    <button name="action" value="subscribe">{% trans 'Subscribe' %}</button>
                    <button disabled>{% trans 'Describe' %}</button>
                {% endif %}
            </form>
            
        </p>
    {% endfor %}
{% endblock content %}